config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
 
  
  resources :users, except: [:destroy, :index, :new]
  get 'register', to: 'users#new'
  
  resources :posts, except: [:destroy] do
    member do
      post 'vote'
      end
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  
  resources :categories, except: [:destroy]

   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   get 'logout', to: 'sessions#logout'
 # resources :sessions, only: [:new, :create, :destroy] alternative using restful resources
  
end

app/models/Category.rb
class Category < ActiveRecord::Base
  include Sluggable
  
  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  sluggable_column :name

end

app/models/Comment.rb
class Comment < ActiveRecord::Base
  include Votable
  belongs_to :post
  belongs_to :user
  
  validates :body, presence: true
  
  
end

app/models/Post_Category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Votable
  include Sluggable
  
  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through:  :post_categories
  
  validates :title, :description, presence: true 
  
  sluggable_column :title
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  
  has_many :posts
  has_many :comments
  has_many :votes
  
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
  
  has_secure_password validations: false
  
  sluggable_column :username
  
  def admin?
    self.role == 'admin'
  end
  
  def moderator?
    self.role == 'moderator'
  end
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
  
  validates_uniqueness_of :user_id, scope: [:voteable_type, :voteable_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?  #declaring the helper methods makes these methods available to all controllers and views
  
  def current_user
    @current_user ||  User.find(session[:user_id]) if session[:user_id]
  end 
  
  def logged_in?
    !!current_user # turns current user into boolean
  end 
  
  def require_user
    if !logged_in?
      flash[:error] = "You need to be logged in to do that"
      redirect_to root_path
    end  
  end
  
  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end
  
  def access_denied
    flash[:error] = 'You are not authorised to do that'
    redirect_to root_path
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_admin, only: [:new, :create]
  def index
    @categories = Category.all
  end
    
  def show
    @category = Category.find_by slug: params[:id]
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_strong_params)
    if @category.save
      flash[:notice] = "Category successfully created"
      redirect_to categories_url
    else
      render :new
    end
  end
  
  def edit
    @category =Category.find_by slug: params[:id]
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_strong_params)
      redirect_to categories_url
    else
      render :edit
    end
  end
  
  #def destroy
  #end
  
  private
  def category_strong_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user, except: [:show, :index]
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.user = current_user
    if @comment.save

      flash[:notice] = "Comment added"
      redirect_to post_url(@post)
    else
      render 'posts/show'
    end
  end
  
  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote was created'
         else
          flash[:error] = 'Your vote was not counted - you can only vote once'
        end
        redirect_to :back
      end
      format.js
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator, only: [:edit, :update]
  
  
  def index
    @posts = Post.all.page(params[:page]).per(3)
  end
    
  def show
      @post = Post.find_by(slug: params[:id])
      @comment = Comment.new
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_strong_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post successfully created"
      redirect_to posts_url
    else
      render :new
    end
  end
  
  def edit
    @post =Post.find_by(slug: params[:id])
  end
  
  def update
    @post = Post.find_by(slug: params[:id])
    if @post.update(post_strong_params)
      redirect_to posts_url
    else
      render :edit
    end
  end
  
  def destroy
  end
  
  def vote
    @post = Post.find_by(slug: params[:id])
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote was created'
         else
          flash[:error] = 'You can only vote once'
        end
        redirect_to :back
      end
      format.js
    end
  end
      
  
  private
  def post_strong_params
    params.require(:post).permit(:title, :url, :description, category_ids:[])
  end
  
  def set_post
    @post = Post.find_by slug: params[:id]
  end
  
  def require_creator
    access_denied unless logged_in? and (current_user == @post.user|| current_user.admin?)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you are now logged in"
      redirect_to root_path
    else
      flash.now[:error] = "There is something wrong with your username or password"
      render :new
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "You've logged out - See you again soon"
    redirect_to root_path
  end
  
 
 
  private 
  
 
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_same_user, only: [:edit, :update]
  
  def show 
    @user = User.find_by(slug: params[:id])
    @posts = @user.posts
    @comments = @user.comments
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_strong_params)
    @user.password = params[:user][:password]
    if @user.save
      flash[:notice] = "New User successfully created"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit 
    @user = User.find_by(slug: params[:id])
  end
  
  def update
    @user = User.find(current_user)
    if @user.update(user_strong_params)
      flash[:notice] = "User successfully updated"
      redirect_to root_path
    else
      render :edit
    end
  end
 
  private
  def user_strong_params
    params.require(:user).permit(:username, :password, :time_zone)
  end
  
  def require_same_user
    if current_user[:slug] != params[:id]
      flash[:error] = "You cannot edit another user's profile"
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def fix_url(url)
   if url.starts_with?('http://www')
       url
     elsif  url.starts_with?('www')
        "http://#{url}"
     elsif  url.starts_with?('https:') 
       url
     else 
        "http://www.#{url}"
    end
  end
  
  def display_datetime(dt)
    if logged_in? && !current_user.time_zone.blank?
      dt = dt.in_time_zone(current_user.time_zone)
    end
    
    dt.strftime("%A, %e %b %Y, %H:%M, %Z")
  end
  
end

app/views/categories/_form.html.erb
<%# partial for category %>
<div class="well">
<%= render "shared/errors", obj: @category %>
<%= form_for @category do |f| %>

	<div class="control-group">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
<div class="control-group">
	<%= f.submit (@category.new_record? ? "Create New Category" : "Update Category"), class: 'btn btn-success'%>
  <%= link_to 'Back', request.referer, class: 'btn btn-link '%>
</div>
	<% end %>
</div>

app/views/categories/edit.html.erb
<h4>Edit Category</h4>
<%= render 'form'%>

app/views/categories/index.html.erb
<h4>List of all Categories<span>
<% if logged_in? %>
<%= link_to "Create a new category", new_category_path,  class: 'btn btn-success pull-right' %></span>
<% end %>
</h4>
<br/>
<% @categories.each do |category| %>
<div class= "well well-lg"></strong> <%=link_to "<strong>#{category.name}</strong>".html_safe, category_path(category) %>
<% if logged_in? %>
<%= link_to "Edit", edit_category_path(category), :class => 'pull-right' %>
<% end %>
</div>
<% end %>
</ul>

app/views/categories/new.html.erb
<h4> New Category</h4>
<%= render 'form' %>

app/views/categories/show.html.erb
<h4>Category<span class='lead'>  <%= @category.name %></span></h4>	
	<hr/>
	<% if logged_in?%>
		<%= link_to "Edit", edit_category_path(@category), class: "btn btn-success"%>
	<% end %>
	<%= link_to "Back to Index", categories_path, class: "btn btn-link" %>
<hr />
	<% @category.posts.each do |post| %>
	<%= render 'posts/post', post: post %>
	<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class="row">
	<div class="span0 well well-small text-center">
		<% if logged_in? %>
			<%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: 'true' do %>
			<i class='icon-arrow-up'></i>
			<% end %>
		<% end %>
		<span id="comment_<%= comment.id %>_up_vote"> <%= comment.up_votes %> </span>
		<br/>
		Votes
		<br/>
		<% if logged_in? %>
			<%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: 'true' do %>
			<i class='icon-arrow-down'></i>
			<% end %>
		<% end %>
		<span id="comment_<%= comment.id %>_down_vote"> <%= comment.down_votes %> </span>
	</div> 

	<div class="span 8 well well-small">
		<em>"<%= comment.body %>"</em>
		<% if show_post %>
		on <%= link_to comment.post.title, post_path(comment.post) %>
		<% end %>
		<br>
		<span class="quiet"> by </span><%= link_to comment.user.username, user_path(comment.user) %>
		<span class="quiet"> <%=ozdate(comment.created_at)%> </span> 
	</div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>

$("#comment_<%= @comment.id %>_up_vote").html("<%= @comment.up_votes %>");
$("#comment_<%= @comment.id %>_down_vote").html("<%= @comment.down_votes %>");
<% else %>
alert('Vote not counted - You can only vote once');
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

	
		<div class="btn-group">
		  <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
		    Category
		    <span class="caret"></span>
		  </a>
				
		  <ul class="dropdown-menu">
			<%	Category.all.each do |category| %>
				  <li> 
						<%= link_to category.name, category_path(category) %>
					</li>
				<% end %>
        
				<% if logged_in? and current_user.admin? %>	
					<li class="divider"></li>
					<li>
						<%= link_to(new_category_path) do %>
						<i class="icon-plus"></i>
						New Category
						<% end %> 
					</li>
				<% end %>
		  </ul>
		</div>
<% if logged_in? %>		
<span class="nav-item">
	<%= link_to 'Create New Post', new_post_path, class: "btn btn-small btn-success" %>
</span>
<% end %>

<span class="pull-right">
<% if logged_in? %>
	<div class="btn-group">
		<a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="#">
			<%= current_user.username.titleize %> 
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
			<li>	<%= link_to 'Log Out', logout_path %> </li>
			<li>  <%= link_to 'Edit Profile', edit_user_path(current_user)%> </li>
			<li>  <%= link_to  'Show Profile', user_path(current_user)%>
		</ul>
	</div>
<% else %>
	<%= link_to 'Log in', login_path, class: "btn btn-small btn-success" %>
	<%= link_to 'Register', register_path, class: "btn btn-small btn-success" %>
<% end %>
</span>
	

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%# partial entered into new, edit forms%>
<%= render 'shared/errors', obj: @post %>

<%= form_for @post do |f| %>


<%= f.label :title %>
<%= f.text_field :title %>
<br/>
<%= f.label :description %>
<%= f.text_area :description %>

<br/>
<%= f.label :url %>
<%= f.text_field :url %>
<br/>
<div class='control-group'>
	<%= f.label "Categories" %>
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text } %>
<% end %>
</div>
<%= f.submit (@post.new_record? ? "Create New Post" : "Update Post"), class: 'btn btn-success'%>
<%= link_to 'Back', request.referer, class: 'btn btn-link '%>

<% end %>
 

app/views/posts/_post.html.erb
<div class="row">
	<%# following code creates an error message - that is processed by ajax %>
	<%# this provides an alternative to the alert and is more in keeping with the sites theme %>
	<div id="post_vote_error_<%= post.to_param %>" class="alert alert-error" style="display: none">
		You have already voted on '<%= post.title %>'. You can only vote on each post once!
	</div>
	<%# end of error code %>
	<div class="span0 well text-center">
		<% if logged_in? %>
			<%= link_to vote_post_path(post, vote: true), method: 'post' , remote: true do %>
				<i class='icon-arrow-up'></i>
			<% end %>
		<% end %>
		<span id="post_<%= post[:id] %>_up_vote"><%= post.up_votes %></span>
		<br/>
		Votes
		<br/>
		<% if logged_in? %>
			<%= link_to vote_post_path(post, vote: false), method: 'post', remote: true  do %>
				<i class='icon-arrow-down'></i>
			<% end %>
		<% end %>
		<span id="post_<%= post[:id] %>_down_vote"><%= post.down_votes %></span>
	</div>  

	<div class= "span8 well well-lg">
	<% post.categories.each do |category| %>
	<span class="badge">
	<%= link_to category.name , category_path(category) %>
  </span>
	<% end %>
	<span class="pull-right quiet"><%= display_datetime(post.created_at) %></span>
	<h5>
	<span><%=link_to post.title, post_path(post) %></span>
	<% if params[:controller] != 'users'%>
	<span class="muted"> by </span> 
		<%= link_to post.user.username.titleize, user_path(post.user) %>
	<% end %>
	</h5>
<em>
	"<%= post.description %>"
</em>
	<br/>
	<%=link_to(post.url, "#{fix_url(post.url)}") %>
	<br/>
	<% if params[:action] == 'index' %>
	<%= link_to "#{post.comments.size} Comments", post_path(post)  %>
	<% end %>
		<% if logged_in? %>
			<% if post[:user_id] == current_user[:id] || current_user.admin? %>
			<span class="pull-right">	<%= link_to "Edit Post", edit_post_path(post)%>
			<% end %>
		<% end %>
	</div>
</div>

app/views/posts/edit.html.erb
<h4>Edit post</h4>
<%= render 'form' %>
 

app/views/posts/index.html.erb
<h3>Welcome to the Postit App</h3>
<h4>List of all posts</h4>


<div> <%= paginate @posts %> </div>

<br/>
<% @posts.each do |post| %>
<%= render 'post', :post => post %>

<% end %>

app/views/posts/new.html.erb
<h4>Create a new post</h4>
<%= render 'form' %>
 

app/views/posts/show.html.erb
<h4>Post</h4>

<%= render 'post', post: @post %>

<% if logged_in? %>
		<%= form_for [@post,@comment] do |f| %>
		<%= render 'shared/errors', obj: @comment %>
		<div class='control-group'>
			<%= f.label :body, 'Leave a comment'%>
			<%= f.text_area :body, rows: 3, class: 'span4' %>
		</div>
		<%= f.submit class: "btn btn-small btn-success" %>
		<% end %>
<% end %>
		<h5>Comments:</h5>
		<% @post.comments.each do |comment| %>
<%= render 'comments/comment', comment: comment %>
<% end %>
	

app/views/posts/vote.js.erb
<% if @vote.valid? %>

$("#post_<%= @post.id %>_up_vote").html("<%= @post.up_votes %>");
$("#post_<%= @post.id %>_down_vote").html("<%= @post.down_votes %>");
<% else %>
  // alert('Vote not counted You can only vote on "<%= @post.title %>" once');
	$("#post_vote_error_<%= @post.to_param %>").show();
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger" role="alert"><p><strong> Input error:  </strong></p>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>	
		</ul>
	</div>
	<% end %>

app/views/users/_form.html.erb
<%# partial for users %>
<%= render "shared/errors", obj: @user %>
<%= form_for @user do |f| %>
	<div class="well">
		<div class="control-group">
	
			<%= f.label :username %>
			<%= f.text_field :username %>
		</div>
	
			<div class="control-group">
			<%= f.label :password, 'Password'%>
			<%= f.password_field :password %>
		</div>

			<div class="control-group">
			<%= f.label :time_zone, 'Time zone'%>
			<%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.all, default: Time.zone.name  %>
		</div>

		<div class="control-group">
			<%= f.submit (@user.new_record? ? "Register New User" : "Update User"), class: 'btn btn-success'%>
			<%= link_to "Back", root_path , class: 'btn btn-link'%>
		</div>
	</div>
<% end %>

app/views/users/edit.html.erb
<h4>Edit User </h4>
<%= render 'form' %>

app/views/users/new.html.erb
<h4>Register a new user</h4>
<%= render 'form' %>

app/views/users/show.html.erb
<h4 class="lead"><%= @user.username.titleize %>s Profile</h4>
<hl/>
<div class="well"> 
  <dl class='dl-horizontal'>
    <dt>Username:</dt>
    <dd><%=@user.username %></dd>
    <dt>Time zone:</dt>
    <dd><%=@user.time_zone %></dd>
  </dl>
</div>	

<ul class="nav nav-tabs">

  <li class=<%='active' if params[:tab].nil? %> >
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user)%>
  </li>
  
  <li class=<%= 'active' if params[:tab] == 'comments'%> >
		<%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
		</li>

</ul>
<% if params[:tab].nil? %>
	<% @posts.each do |post| %>
	<%= render 'posts/post', post: post %>
	<% end %>
<% elsif params[:tab] == 'comments'%>
	<% @comments.each do |commenting| %>
	<%= render 'comments/comment', comment: commenting, show_post:  true %>
	<% end %>
<% end %>